name: Publish

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        default: true
    - name: cargo install cargo-workspaces
      uses: actions-rs/cargo@v1
      with:
        command: install
        args: cargo-workspaces --version 0.2.35
    - name: Publish
      uses: actions-rs/cargo@v1
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_ACCESS_TOKEN }}
      with:
        command: workspaces
        args: publish --yes --from-git --skip-published
